### ISSUE TITLE
Cannot get button events

### ISSUE THREAD

**Issue by ghost** [AdrianFlorian/AFImageViewer#1]
Hi,
Thank you for the ImageViewer. I'm using buttons for menus instead of images. However, I cant get the click event of the buttons. Perhaps due to the overlaying ARScrollViewEnhancer. Could you please help with this? I'm a little short on time so any assistance is much appreciated :)

**Comment by ghost** [comment]
Wrong project, my bad :(

**Comment by AdrianFlorian** [comment]
haha, no problem :)
