### ISSUE TITLE
Doesn't obey UIPageControl hidesForSinglePage property

### ISSUE THREAD

**Issue by ekdevdes** [AdrianFlorian/AFImageViewer#2]
going into AFImageViewer.m and putting `self.pagecontrol.hidesForSinglePage = YES`
 right below the other `UIPageControl` config lines doesn't hide the page control dots when there's only a single page in the image view.

**Comment by AdrianFlorian** [comment]
thanks for reporting the issue, I'll solve it and get back to you ;)
