### ISSUE TITLE
Doesn't work with dynamically created images

### ISSUE THREAD

**Issue by ekdevdes** [AdrianFlorian/AFImageViewer#3]
I tried using this with dynamically created UIImages. I.e. Turning a UIView into an UIImage then adding to the images array and reloading the image view by reseting the `images` property but it doesn't work for dynamically created images

**Comment by ShadeApps** [comment]
It does work if you call 'layoutSubviews' on it, so you are wrong.

**Comment by AdrianFlorian** [comment]
Ok, then I'll close this :+1:
